name: Build Flutter Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Check Flutter
        run: flutter --version

      - name: Enable Windows
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Drift files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Windows
        run: flutter build windows --release

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "build/windows/x64/runner/Release/*" `
            -DestinationPath "flutter-windows-release.zip" `
            -Force

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: flutter-windows-release
          path: flutter-windows-release.zip
          if-no-files-found: error
          retention-days: 14